In [1]:
import pandas as pd

plant1 = pd.read_csv('./plant1_train.csv',parse_dates=['plant1_train.mea_ddhr'])
plant1.head(10)

Unnamed: 0 plant1_train.mea_ddhr  plant1_train.tem_in_loc1  \
0           1   2016-04-01 00:00:00                      16.0   
1           2   2016-04-01 03:00:00                      14.0   
2           3   2016-04-01 06:00:00                      13.0   
3           4   2016-04-01 09:00:00                      13.0   
4           5   2016-04-01 12:00:00                      16.0   
5           6   2016-04-01 15:00:00                      18.0   
6           7   2016-04-01 18:00:00                      17.0   
7           8   2016-04-01 21:00:00                      16.0   
8           9   2016-04-02 00:00:00                      15.0   
9          10   2016-04-02 03:00:00                      14.0   

   plant1_train.hum_in_loc1  plant1_train.tem_coil_loc1  \
0                      24.0                        11.0   
1                      28.0                        10.0   
2                      33.0                        10.0   
3                      33.0                        10.0   
4                      28.0                        10.0   
5                      24.0                        14.0   
6                      28.0                        14.0   
7                      38.0                        12.0   
8                      41.0                        12.0   
9                      41.0                        10.0   

   plant1_train.tem_in_loc2  plant1_train.hum_in_loc2  \
0                      14.0                      23.0   
1                      12.0                      32.0   
2                      11.0                      37.0   
3                      11.0                      35.0   
4                      15.0                      27.0   
5                      18.0                      21.0   
6                      17.0                      29.0   
7                      15.0                      36.0   
8                      14.0                      43.0   
9                      12.0                      44.0   

   plant1_train.tem_coil_loc2  plant1_train.tem_in_loc3  \
0                        11.0                      13.0   
1                         9.0                      11.0   
2                         9.0                      10.0   
3                         9.0                      10.0   
4                        11.0                      14.0   
5                        14.0                      16.0   
6                        14.0                      15.0   
7                        12.0                      14.0   
8                        12.0                      13.0   
9                         9.0                      12.0   

   plant1_train.hum_in_loc3  plant1_train.tem_coil_loc3  \
0                      32.0                        10.0   
1                      42.0                         7.0   
2                      44.0                         7.0   
3                      41.0                         8.0   
4                      30.0                         9.0   
5                      27.0                        12.0   
6                      38.0                        12.0   
7                      41.0                        11.0   
8                      49.0                        11.0   
9                      49.0                         8.0   

   plant1_train.tem_out_loc1  plant1_train.hum_out_loc1  \
0                        9.0                       42.0   
1                        7.0                       59.0   
2                        6.0                       56.0   
3                       18.0                       30.0   
4                       18.0                       20.0   
5                       17.0                       23.0   
6                       12.0                       52.0   
7                       11.0                       55.0   
8                       10.0                       57.0   
9                       10.0                       54.0   

   plant1_train.cond_loc1  plant1_train.cond_loc2  plant1_t

In [2]:
del plant1['Unnamed: 0']

In [3]:
plant1["year"] = plant1["plant1_train.mea_ddhr"].dt.year
plant1["month"] = plant1["plant1_train.mea_ddhr"].dt.month
plant1["day"] = plant1["plant1_train.mea_ddhr"].dt.day
plant1["hour"] = plant1["plant1_train.mea_ddhr"].dt.hour
plant1["minute"] = plant1["plant1_train.mea_ddhr"].dt.minute
plant1["second"] = plant1["plant1_train.mea_ddhr"].dt.second
plant1.head()

plant1_train.mea_ddhr  plant1_train.tem_in_loc1  plant1_train.hum_in_loc1  \
0   2016-04-01 00:00:00                      16.0                      24.0   
1   2016-04-01 03:00:00                      14.0                      28.0   
2   2016-04-01 06:00:00                      13.0                      33.0   
3   2016-04-01 09:00:00                      13.0                      33.0   
4   2016-04-01 12:00:00                      16.0                      28.0   

   plant1_train.tem_coil_loc1  plant1_train.tem_in_loc2  \
0                        11.0                      14.0   
1                        10.0                      12.0   
2                        10.0                      11.0   
3                        10.0                      11.0   
4                        10.0                      15.0   

   plant1_train.hum_in_loc2  plant1_train.tem_coil_loc2  \
0                      23.0                        11.0   
1                      32.0                         9.0   
2                      37.0                         9.0   
3                      35.0                         9.0   
4                      27.0                        11.0   

   plant1_train.tem_in_loc3  plant1_train.hum_in_loc3  \
0                      13.0                      32.0   
1                      11.0                      42.0   
2                      10.0                      44.0   
3                      10.0                      41.0   
4                      14.0                      30.0   

   plant1_train.tem_coil_loc3  ...  plant1_train.hum_out_loc1  \
0                        10.0  ...                       42.0   
1                         7.0  ...                       59.0   
2                         7.0  ...                       56.0   
3                         8.0  ...                       30.0   
4                         9.0  ...                       20.0   

   plant1_train.cond_loc1  plant1_train.cond_loc2  plant1_train.cond_loc3  \
0                     0.0                     0.0                     0.0   
1                     0.0                     0.0                     0.0   
2                     0.0                     0.0                     0.0   
3                     0.0                     0.0                     0.0   
4                     0.0                     0.0                     0.0   

   year  month  day  hour  minute  second  
0  2016      4    1     0       0       0  
1  2016      4    1     3       0       0  
2  2016      4    1     6       0       0  
3  2016      4    1     9       0       0  
4  2016      4    1    12       0       0  

[5 rows x 21 columns]

In [4]:
print(plant1.keys())

Index(['plant1_train.mea_ddhr', 'plant1_train.tem_in_loc1',
       'plant1_train.hum_in_loc1', 'plant1_train.tem_coil_loc1',
       'plant1_train.tem_in_loc2', 'plant1_train.hum_in_loc2',
       'plant1_train.tem_coil_loc2', 'plant1_train.tem_in_loc3',
       'plant1_train.hum_in_loc3', 'plant1_train.tem_coil_loc3',
       'plant1_train.tem_out_loc1', 'plant1_train.hum_out_loc1',
       'plant1_train.cond_loc1', 'plant1_train.cond_loc2',
       'plant1_train.cond_loc3', 'year', 'month', 'day', 'hour', 'minute',
       'second'],
      dtype='object')


In [5]:
print(plant1.shape)

(58749, 21)


In [6]:
plant1_linear = plant1.interpolate(method ='linear') 

In [7]:
print(plant1_linear.shape)

(58749, 21)


In [8]:
Y1 = plant1_linear[['plant1_train.cond_loc1']]
Y2 = plant1_linear[['plant1_train.cond_loc2']]
Y3 = plant1_linear[['plant1_train.cond_loc3']]
Y = plant1_linear[['plant1_train.cond_loc1','plant1_train.cond_loc2','plant1_train.cond_loc3']]
X = plant1_linear.drop(['plant1_train.mea_ddhr','plant1_train.cond_loc1','plant1_train.cond_loc2','plant1_train.cond_loc3'],axis=1)

In [9]:
print(X.keys())

Index(['plant1_train.tem_in_loc1', 'plant1_train.hum_in_loc1',
       'plant1_train.tem_coil_loc1', 'plant1_train.tem_in_loc2',
       'plant1_train.hum_in_loc2', 'plant1_train.tem_coil_loc2',
       'plant1_train.tem_in_loc3', 'plant1_train.hum_in_loc3',
       'plant1_train.tem_coil_loc3', 'plant1_train.tem_out_loc1',
       'plant1_train.hum_out_loc1', 'year', 'month', 'day', 'hour', 'minute',
       'second'],
      dtype='object')


In [10]:
from sklearn.model_selection import train_test_split

X1_train, X1_test, Y1_train, Y1_test = train_test_split(X,Y1,test_size=0.2,shuffle=True)
X2_train, X2_test, Y2_train, Y2_test = train_test_split(X,Y2,test_size=0.2,shuffle=True)
X3_train, X3_test, Y3_train, Y3_test = train_test_split(X,Y3,test_size=0.2,shuffle=True)

In [11]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [12]:
model = LogisticRegression(C=1000,random_state=0,solver='liblinear')

In [13]:
model.fit(X1_train,Y1_train.values.ravel())

LogisticRegression(C=1000, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [14]:
pred1_proba = model.predict_proba(X1_test)

In [15]:
pred1 = model.predict(X1_test)

In [16]:
print(pred1_proba)

[[1.00000000e+00 1.01227185e-28]
 [1.00000000e+00 1.06187280e-38]
 [1.00000000e+00 3.31600777e-20]
 ...
 [1.00000000e+00 2.08536729e-23]
 [1.00000000e+00 2.19245329e-34]
 [1.00000000e+00 2.79660130e-21]]


In [18]:
print("loc1 테스트 세트 정확도: {:.3f}".format(metrics.roc_auc_score(Y1_test,pred1)))

loc1 테스트 세트 정확도: 0.958


In [ ]:
# print("loc1 테스트 세트 정확도: {:.3f}".format(metrics.roc_auc_score(Y1_test,pred1)))

In [19]:
for i in range(len(pred1_proba)):
    if pred1_proba[i][1] > pred1_proba[i][0]:
        print(i)

359
459
782
1132
1389
1437
1516
2019
2632
2714
2828
3445
3845
4150
4302
4358
4502
4645
5088
5209
5399
5733
5868
5895
6056
6337
6374
6421
6426
6542
7114
8116
8247
8904
9120
9745
10117
10271
10328
10775
10939
10962
11040
11058
11407
11548


In [20]:
print(pred1_proba[10271])

[8.58971683e-04 9.99141028e-01]


In [ ]:
# print(round(pred1,2))

In [21]:
print(pred1)

[0. 0. 0. ... 0. 0. 0.]


In [22]:
from sklearn.metrics import confusion_matrix

confusion1 = confusion_matrix(Y1_test, pred1)

In [23]:
print(confusion1)

[[11700     2]
 [    4    44]]
